GET http://localhost:3030/authors

####

POST http://localhost:3030/authors
Content-Type: application/json

{
    "name": "",
    "surname": "",
    "email": "",
    "dateOfBirth": "",
    "avatar": ""
}

####

GET http://localhost:3030/authors/65f0650dc95202c79d1b1982

####

PATCH http://localhost:3030/authors/65f0650dc95202c79d1b1982
Content-Type: application/json

{
    "avatar": "Hixyllian"
}


####

DELETE http://localhost:3030/authors/65f06bf840f1ecd677688d5d